[package]
name = "high_low"
version = "0.1.0"
edition = "2021"
authors = ["jake@jakerandall.me"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4.0"